name: Compile Marauder Bin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install ESP32 Platform and Compile
      run: |
        arduino-cli core update-index
        arduino-cli core install espressif:esp32
        cd esp32_marauder
        # This will verify the code compiles without errors
        echo "Building sketch..."
