name: Compile Marauder Bin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Force Headless No-SD Compilation
      run: pio run -e esp32dev --opt="-DGENERIC_ESP32 -DHEADLESS"

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Marauder-WROOM32-NoSD
        path: .pio/build/esp32dev/firmware.bin
