name: Compile Marauder Bin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Compile Touchscreen Firmware Without SD
      run: pio run -e esp32_v4 --opt="-UHAS_SD -UUSE_SD"

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Marauder-Touchscreen-NoSD
        path: .pio/build/esp32_v4/firmware.bin

